name: Deploy via SSH (Hostinger split app/public)

on:
  push:
    branches: [ main ]

env:
  SUBDIR: vibe-playlistsw   # <<--- your Laravel folder in the repo

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.HOST_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p ${{ secrets.HOST_SSH_PORT }} ${{ secrets.HOST_SSH_HOST }} >> ~/.ssh/known_hosts

      # Optional: build Vite assets so your public pages using @vite get CSS/JS.
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build assets (Vite)
        working-directory: ./${{ env.SUBDIR }}
        run: |
          npm ci
          npm run build

      - name: Create tarball to upload
        run: |
          tar -C "${{ env.SUBDIR }}" -czf /tmp/app.tar.gz \
            --exclude='.git' \
            --exclude='node_modules' \
            --exclude='vendor' \
            .

      - name: Upload bundle to server
        run: |
          scp -i ~/.ssh/id_ed25519 -P ${{ secrets.HOST_SSH_PORT }} /tmp/app.tar.gz \
            ${{ secrets.HOST_SSH_USER }}@${{ secrets.HOST_SSH_HOST }}:/home/${{ secrets.HOST_SSH_USER }}/app.tar.gz

      - name: Deploy on server (composer + artisan)
        env:
          APP_DIR: ${{ secrets.HOST_APP_DIR }}       # e.g. /home/u2060xxxxx/app
          PUB_DIR: ${{ secrets.HOST_PUBLIC_DIR }}    # e.g. /home/u2060xxxxx/public_html
        run: |
          ssh -i ~/.ssh/id_ed25519 -p ${{ secrets.HOST_SSH_PORT }} ${{ secrets.HOST_SSH_USER }}@${{ secrets.HOST_SSH_HOST }} bash -euo pipefail -lc "
            mkdir -p \"\$APP_DIR\" \"\$PUB_DIR\"
            tar -xzf ~/app.tar.gz -C \"\$APP_DIR\"
            rm -f ~/app.tar.gz

            # Composer (install locally if missing)
            if ! command -v composer >/dev/null 2>&1; then
              mkdir -p ~/bin
              php -r \"copy('https://getcomposer.org/installer','composer-setup.php');\"
              php composer-setup.php --install-dir=\$HOME/bin --filename=composer
              rm composer-setup.php
              export PATH=\"\$HOME/bin:\$PATH\"
            fi

            cd \"\$APP_DIR\"
            composer install --no-dev --prefer-dist --optimize-autoloader

            php artisan key:generate --force || true
            php artisan migrate --force || true
            php artisan config:cache && php artisan route:cache && php artisan view:cache || true

            # Put Hostinger index that forwards to app/public/index.php
            cp -f \"\$APP_DIR/index.hostinger.php\" \"\$PUB_DIR/index.php\"
          "
